### ISSUE TITLE
vanilla mods?

### ISSUE THREAD

**Issue by solanuscasey** [eaglerforge/EaglerForgeInjector#31]
can vanilla mods be loaded? if not, is there a database somewhere where I can find eagler mods?(specifically the manhunt compass)
If this is the wrong spot to put this, let me know so I can take it down and move It to the correct location.

**Comment by OtterCodes101** [comment]
EaglerForge's API is completely different than Forge's. Mods need to be made from scratch.

**Comment by STPv22** [comment]
Ill look into the manhunt compass
