### ISSUE TITLE
Hmm... (gun mod not working)

### ISSUE THREAD

**Issue by STPv22** [eaglerforge/EaglerForgeInjector#44]
[Screen recording 2024-12-09 8.26.13 AM.webm](https://github.com/user-attachments/assets/d57f22c4-dade-4869-a068-86336c1512a1)

**Comment by STPv22** [comment]
let me try using a newer version of eaglerforge, that might be it.

**Comment by OtterCodes101** [comment]
you need to be using the latest version of EaglerForge before making a bug report.

**Comment by STPv22** [comment]
sorry :3
