### ISSUE TITLE
Idea to load mod meta before client launch/ModAPI fully loaded

### ISSUE THREAD

**Issue by STPv22** [eaglerforge/EaglerForgeInjector#7]
The idea is to run mod function when mods would normally load, because of GUI launching before mods load
```
(() => {
    ModAPI.meta.title("Mod");
    
    ModAPI.mod(exampleMod); //idk ModAPI.regMod()?

    function exampleMod() {
             
    }
})();
```

**Comment by STPv22** [comment]
it would complicate mod making a bit, but it would be worth it. at least so you don't have to manually do `if (ModAPI.litterallyEverthing != undefined) doModStuff();`

**Comment by STPv22** [comment]
update, might be better: 
```
ModAPI.registerMod(() => {
var meta  = {
title: "IDFK",
desciption: "yup, words"
}

return meta;
})
```

**Comment by ZXMushroom63** [comment]
There are already too many mods using an older structure, at this point in time a large syntax change such as this is not viable.

**Comment by STPv22** [comment]
alr

**Comment by cire3wastaken** [comment]
> There are already too many mods using an older structure, at this point in time a large syntax change such as this is not viable.

how is this not viable? there arent that many mods to be affected and its a beneficial change

**Comment by STPv22** [comment]
i mean... i would say all of the examplemods, but its not a big thing to update, and most of them use even listeners...

**Comment by ZXMushroom63** [comment]
> i mean... i would say all of the examplemods, but its not a big thing to update, and most of them use even listeners...

That and there's also the issue of malicious mods, which would be able to modify the mod manager and prevent their uninstallation. There should be no third-party code allowed to run before the game has already been initialized.

**Comment by STPv22** [comment]
> > i mean... i would say all of the examplemods, but its not a big thing to update, and most of them use even listeners...
> 
> That and there's also the issue of malicious mods, which would be able to modify the mod manager and prevent their uninstallation. There should be no third-party code allowed to run before the game has already been initialized.
> 
> Sorry if I'm coming across as harsh or anything, but I've already spotted a 'mod' that was actually an ip-logger, so it's not going to be an unreasonably assumption

where?

**Comment by ZXMushroom63** [comment]
![image](https://github.com/user-attachments/assets/0d5f3f34-c353-4cf4-a54a-3f08f39b0e15)
there.

the point here is that it is entirely possible to get ip-logged and more from mods, and being able to uninstall the malicious mods without them being loaded is an essential feature.

**Comment by STPv22** [comment]
> ![image](https://private-user-images.githubusercontent.com/116805577/373919586-0d5f3f34-c353-4cf4-a54a-3f08f39b0e15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyODA5NjUsIm5iZiI6MTcyODI4MDY2NSwicGF0aCI6Ii8xMTY4MDU1NzcvMzczOTE5NTg2LTBkNWYzZjM0LWMzNTMtNGNmNC1hNTRhLTNmMDhmMzliMGUxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwNTU3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDNmYzUzNGMzNzE5OTJlMjkzY2RmMDUxOGNmODhkMzQ1Mzk1YWE2MDgwY2IzZTUxNGMwODQ1YzNjMmI4MGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._tLgKQjHZUqFLIOtTsjQANcPAZ9V5YfeJi-420kSA0Y) there.
> 
> the point here is that it is entirely possible to get ip-logged and more from mods, and being able to uninstall the malicious mods without them being loaded is an essential feature.

https://www.youtube.com/watch?v=XG-BtJv3UnU 😈

**Comment by STPv22** [comment]
also heres my school ip, please fid a way to screw with them 🙏 
![image](https://github.com/user-attachments/assets/b400225d-270b-4823-94a5-03e3f878a743)

**Comment by ZXMushroom63** [comment]
> also heres my school ip, please fid a way to screw with them 🙏 ![image](https://private-user-images.githubusercontent.com/145866689/374048146-b400225d-270b-4823-94a5-03e3f878a743.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDA3NDgsIm5iZiI6MTcyODMwMDQ0OCwicGF0aCI6Ii8xNDU4NjY2ODkvMzc0MDQ4MTQ2LWI0MDAyMjVkLTI3MGItNDgyMy05NGE1LTAzZTNmODc4YTc0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxMTI3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzRlMzU5NmQ3YTc4ODYyZjlmMmEyZjMyOGMzNWY0MDEzMTJlMTgzOTQ0Y2E5Yjk4Y2MzZGRmZGI3ZDU0MWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SMEs8RAmSP07UiFtp21d2x4jgQXc2TPgwzQ__JLr484)

you understand that you can get locations from ip addresses, right?

**Comment by STPv22** [comment]
> > also heres my school ip, please fid a way to screw with them 🙏
> 
> you understand that you can get locations from ip addresses, right? like are you sure you want this public

yes. its not even my school tbh, its my old one.
